INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Главная', 'index', 0, 'active');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Аренда техники', 'no', 0, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Экскаваторы-погрузчики', 'arenda-jekskavatora-pogruzchika', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Гусечный экскаватор', 'arenda-ekskavatora', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Полноповоротный колесный экскаватор', 'arenda-kolesnogo-ekskavatora', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Ямобур', 'jamobur-v-arendu', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Камаз', 'arenda-samosvala', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Пухто', 'arenda-pyxto', 2, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Услуги', 'no', 0, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Раскорчевка участков', 'raschistka-uchastka', 9, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Выравнивание участка', 'vyravnivanie-zemelnogo-uchastka', 9, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Рытье траншей и котлованов', 'ryte-transhei', 9, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Демонтаж домов', 'demontaj-domov', 9, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Галерея', 'gallery', 0, '');
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Прайс', '#price', 0, null);
INSERT INTO tr.menu (menu_name, link, parent, class) VALUES ('Контакты', '#contacts', 0, '');